// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wpf_projekt.models;

#nullable disable

namespace wpf_projekt.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260410062828_ChangeIntToDecimal")]
    partial class ChangeIntToDecimal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("wpf_projekt.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPositive")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PersonalAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SharedAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TransactionTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PersonalAccountId");

                    b.HasIndex("SharedAccountId");

                    b.HasIndex("TransactionTypeId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("wpf_projekt.models.PersonalAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PersonalAccounts");
                });

            modelBuilder.Entity("wpf_projekt.models.SharedAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<int>("User1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("User2Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("User1Id");

                    b.HasIndex("User2Id");

                    b.ToTable("SharedAccounts");
                });

            modelBuilder.Entity("wpf_projekt.models.TransactionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TransactionTypes");
                });

            modelBuilder.Entity("wpf_projekt.models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Earnings")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SharedAccountId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SharedAccountId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("wpf_projekt.Models.Transaction", b =>
                {
                    b.HasOne("wpf_projekt.models.PersonalAccount", "PersonalAccount")
                        .WithMany("Transactions")
                        .HasForeignKey("PersonalAccountId");

                    b.HasOne("wpf_projekt.models.SharedAccount", "SharedAccount")
                        .WithMany("Transactions")
                        .HasForeignKey("SharedAccountId");

                    b.HasOne("wpf_projekt.models.TransactionType", "TransactionType")
                        .WithMany("Transactions")
                        .HasForeignKey("TransactionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonalAccount");

                    b.Navigation("SharedAccount");

                    b.Navigation("TransactionType");
                });

            modelBuilder.Entity("wpf_projekt.models.PersonalAccount", b =>
                {
                    b.HasOne("wpf_projekt.models.User", "User")
                        .WithMany("PersonalAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("wpf_projekt.models.SharedAccount", b =>
                {
                    b.HasOne("wpf_projekt.models.User", "User1")
                        .WithMany()
                        .HasForeignKey("User1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("wpf_projekt.models.User", "User2")
                        .WithMany()
                        .HasForeignKey("User2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("wpf_projekt.models.User", b =>
                {
                    b.HasOne("wpf_projekt.models.SharedAccount", "SharedAccount")
                        .WithMany()
                        .HasForeignKey("SharedAccountId");

                    b.Navigation("SharedAccount");
                });

            modelBuilder.Entity("wpf_projekt.models.PersonalAccount", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("wpf_projekt.models.SharedAccount", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("wpf_projekt.models.TransactionType", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("wpf_projekt.models.User", b =>
                {
                    b.Navigation("PersonalAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
